### ISSUE TITLE
`solc-select versions` should indicate that there aren't any versions of solc installed instead of erroring

### ISSUE THREAD

**Issue by 0xalpharush** [trailofbits/solc-select#152]
If you run `solc-select versions` in a fresh venv, it's expected that solc isn't installed. The error message could be more helpful instead of the current behavior:
```
(slither) alpharush@macbook slither % solc-select versions
Traceback (most recent call last):
  File "/opt/homebrew/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
             ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/__main__.py", line 64, in solc_select
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/solc-select/1.0.2/libexec/lib/python3.11/site-packages/solc_select/solc_select.py", line 60, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.
```

**Comment by elopez** [comment]
Closing as this got released in [v1.0.4](https://github.com/crytic/solc-select/releases/tag/v1.0.4)
