### ISSUE TITLE
solc-select v1.0.0 v1.0.3 doesn't install anything whereas everything works fine with v0.2.0

### ISSUE THREAD

**Issue by mialgotech** [trailofbits/solc-select#179]
- OS details:

`uname -a` :

`Linux pop-os 5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S x86_64 x86_64 x86_64 GNU/Linux`

- v1.0.3 : 

>  `pip3 install solc-select` installs `solc-select-1.0.3`
>  `solc-select install` just prints `Available versions to install:` and the cursor keeps on blinking unless I hit Ctrl+C
>  `solc --version` throws `argparse.ArgumentTypeError: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION 
>   environment variable.` error
>   None of the commands result into any output. The cursor keeps on blinking

- Similar issue with v1.0.0

- There is no issue with v0.2.0. Everything works as expected.

**Comment by V1C70RYG0D** [comment]
i also faced the same problem, i am using Garuda Linux [arch-based],
in actual i get connection time out error after few minutes like this 
```
solc-select install 0.4.21
Traceback (most recent call last):
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 1283, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 1329, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 1278, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 1038, in _send_output
self.send(msg)
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 976, in send
self.connect()
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 1448, in connect
super().connect()
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/http/client.py", line 942, in connect
self.sock = self._create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/socket.py", line 851, in create_connection
raise exceptions[0]
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/socket.py", line 836, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/victorygod/smart contract audit/hehe/bin/solc-select", line 10, in <module>
sys.exit(solc_select())
^^^^^^^^^^^^^
File "/home/victorygod/smart contract audit/hehe/lib/python3.11/site-packages/solc_select/__main__.py", line 58, in solc_select
install_artifacts(args.get(INSTALL_VERSIONS))
File "/home/victorygod/smart contract audit/hehe/lib/python3.11/site-packages/solc_select/solc_select.py", line 75, in install_artifacts
releases = get_available_versions()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/victorygod/smart contract audit/hehe/lib/python3.11/site-packages/solc_select/solc_select.py", line 230, in get_available_versions
github_json = urllib.request.urlopen(list_url).read()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 519, in open
response = self._open(req, data)
^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 536, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
result = func(*args)
^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
return self.do_open(http.client.HTTPSConnection, req,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by harshbansal6** [comment]
whats the solution?

**Comment by mialgotech** [comment]
Didn't bother with 1.0.x anynore. Went with v0.2.0.

**Comment by rupen-pedalsup** [comment]
@mialgotech https://github.com/crytic/solc-select/issues/205#issuecomment-1825171056

**Comment by elopez** [comment]
Closing this issue as it has not had activity for a while, and the errors appear to be connectivity problems to GitHub. If you are still experiencing issues on the latest release feel free to create a new issue.
