### ISSUE TITLE
[Bug-Candidate]: urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by jgvbuygu** [trailofbits/solc-select#212]
### Describe the issue:

(GTNN) zss@yyy-Precision-5820-Tower-X-Series:/home/hpn/data/brx/Cross/dataset$ solc-select install 0.8.26
Traceback (most recent call last):
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/site-packages/solc_select/__main__.py", line 59, in solc_select
    install_artifacts(args.get(INSTALL_VERSIONS))
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/site-packages/solc_select/solc_select.py", line 91, in install_artifacts
    releases = get_available_versions()
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/site-packages/solc_select/solc_select.py", line 254, in get_available_versions
    github_json = urllib.request.urlopen(list_url).read()
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/hpn/data/fwq/Anaconda3/envs/GTNN/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
Please!!

### Code example to reproduce the issue:

.

### Version:

.

**Comment by elopez** [comment]
Hi, can you confirm if https://raw.githubusercontent.com/ works for you? It sounds similar to this issue https://github.com/crytic/solc-select/issues/205#issuecomment-1825171056 caused by a specific internet provider blocking some GitHub domains.

**Comment by jgvbuygu** [comment]
sorry,I open this website and go back to https://github.com/

**Comment by elopez** [comment]
Closing this issue as it has not had activity for a while. If you are still experiencing issues on the latest release feel free to create a new issue.
