### ISSUE TITLE
When I run the 'Solc select Install' command, the following error occurs. How can I solve it?

### ISSUE THREAD

**Issue by Lsw-98** [trailofbits/solc-select#59]
(py36) lsw@lsw-virtual-machine:~/桌面$ solc-select install
Available versions to install:
Traceback (most recent call last):
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lsw/anaconda3/envs/py36/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/__main__.py", line 48, in solc_select
    for version in get_installable_versions():
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 105, in get_installable_versions
    installable = list(set(get_available_versions()) - set(installed_versions()))
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 115, in get_available_versions
    available_releases.update(get_additional_linux_versions())
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 123, in get_additional_linux_versions
    github_json = urllib.request.urlopen(url).read()
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
(py36) lsw@lsw-virtual-machine:~/桌面$

**Comment by 0xicingdeath** [comment]
Hey @Lsw-98! Thanks for reporting this. This does look like a bug. What OS and version are you using?

**Comment by QinHaoChen97** [comment]
I also have a similar problem "ConnectionResetError" like yours.And I restart the virtual machine then it works.I think the error occur because I use VPN moment ago.

**Comment by shawnwbts** [comment]
Hi,I have met this problem before. But I dont know how to solve this problem. I am using a Linux server and the solc-select version is 0.2.1

> Hey @Lsw-98! Thanks for reporting this. This does look like a bug. What OS and version are you using?

**Comment by shawnwbts** [comment]
> (py36) lsw@lsw-virtual-machine:~/桌面$ solc-select install
> Available versions to install:
> Traceback (most recent call last):
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1318, in do_open
> encode_chunked=req.has_header('Transfer-encoding'))
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1239, in request
> self._send_request(method, url, body, headers, encode_chunked)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1285, in _send_request
> self.endheaders(body, encode_chunked=encode_chunked)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1234, in endheaders
> self._send_output(message_body, encode_chunked=encode_chunked)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1026, in _send_output
> self.send(msg)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 964, in send
> self.connect()
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1392, in connect
> super().connect()
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/http/client.py", line 936, in connect
> (self.host,self.port), self.timeout, self.source_address)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/socket.py", line 722, in create_connection
> raise err
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/socket.py", line 713, in create_connection
> sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/lsw/anaconda3/envs/py36/bin/solc-select", line 8, in
> sys.exit(solc_select())
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/**main**.py", line 48, in solc_select
> for version in get_installable_versions():
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 105, in get_installable_versions
> installable = list(set(get_available_versions()) - set(installed_versions()))
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 115, in get_available_versions
> available_releases.update(get_additional_linux_versions())
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/solc_select/solc_select.py", line 123, in get_additional_linux_versions
> github_json = urllib.request.urlopen(url).read()
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 223, in urlopen
> return opener.open(url, data, timeout)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 526, in open
> response = self._open(req, data)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 544, in _open
> '_open', req)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
> result = func(*args)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1361, in https_open
> context=self._context, check_hostname=self._check_hostname)
> File "/home/lsw/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1320, in do_open
> raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
> (py36) lsw@lsw-virtual-machine:~/桌面$

Sorry to bother you, did you solve this problem?

**Comment by elopez** [comment]
Closing this issue as it has not had activity for a while. If you are still experiencing issues on the latest release feel free to create a new issue.
